### ISSUE TITLE
Why is localization needed for the "Multiselect" component

### ISSUE THREAD

**Issue by nemanja3** [jquense/react-widgets#1064]
hello,
i want to use the "Multiselect" component but then on###  import { Multiselect } from 'react-widgets' i get an error:

![image](https://user-images.githubusercontent.com/26413661/111323546-465baa80-866a-11eb-9ffa-b731763714e6.png)

i instaled: npm install react-widgets --save, and i want to import just multiselect component why do i need to install some localizers ? there is no "format" property in multiselect component ? can i use this component without complicating with some localizers?
thank you

**Comment by jquense** [comment]
you don't need to. The error is a bug where webpack is considering a Typescript type as a real module, instead of just types.

try and reinstall the package now it should be fixed

**Comment by kris2kris** [comment]
Hi,

I am using Yarn and I have the same issue, I deleted node_modules and did yarn install again but I still have the issue...
Do you have any idea ?

Thanks

**Comment by kris2kris** [comment]
Ok I find the problem !
The import like this `import {DropdownList} from 'react-widgets'` are not working anymore...
I must use `import DropdownList from 'react-widgets/DropdownList`
