### ISSUE TITLE
React 15.2.0 and unknown props

### ISSUE THREAD

**Issue by tylergoodman** [jquense/react-widgets#408]
Several of the widgets pass down invalid props as described [here](https://fb.me/react-unknown-prop). Here's some of the ones I've run into:

In Multiselect:
> Warning: Unknown props `caseSensitive`, `ariaActiveDescendantKey` on `<div>` tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in div (created by Multiselect)
>     in Multiselect (created by Uncontrolled(Multiselect))
>     in Uncontrolled(Multiselect)

> Warning: Unknown prop `searchTerm` on `<input>` tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
>     in input (created by MultiselectInput)
>     in MultiselectInput (created by Multiselect)
>     in div (created by Multiselect)
>     in div (created by Multiselect)
>     in Multiselect (created by Uncontrolled(Multiselect))
>     in Uncontrolled(Multiselect)

> Warning: Unknown props `onOpening`, `duration`, `onClosing`, `onClose`, `onOpen` on `<div>` tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in div (created by Popup)
>     in Popup (created by Multiselect)
>     in div (created by Multiselect)
>     in Multiselect (created by Uncontrolled(Multiselect))
>     in Uncontrolled(Multiselect)

and in DateTimePicker:

> Warning: Unknown props `editFormat`, `editing`, `culture`, `parse`, `textValue` on `<input>` tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in input (created by DatePickerInput)
>     in DatePickerInput (created by DateTimePicker)
>     in div (created by DateTimePicker)
>     in DateTimePicker (created by Uncontrolled(DateTimePicker))
>     in Uncontrolled(DateTimePicker)

**Comment by vdh** [comment]
Also triggers for `busy` prop on `Multiselect`

**Comment by vdh** [comment]
It looks like this was fixed in v3.3.4 by 62c1fe6

**Comment by FBosler** [comment]
This isn't fixed for me. How can I fix it?

> Warning: Unknown props `editFormat`, `editing`, `culture`, `parse`, `textValue` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in input (created by DatePickerInput)

> Warning: Unknown props `duration`, `onOpening`, `onClosing`, `onClose`, `onOpen` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in div (created by Popup)

for more see https://github.com/jquense/react-widgets/issues/601
