### ISSUE TITLE
deprecations in react 15.5.0 

### ISSUE THREAD

**Issue by tswaters** [jquense/react-widgets#559]
See the following for details: 

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

createClass has moved from `react` to another package --

```diff
-var Component = React.createClass({
+var createReactClass = require('create-react-class');
+var Component = createReactClass({
```

propTypes have moved from `react` to another package --

```diff
-import React, {PropTypes} from 'react'
+import React from 'react'
+import PropTypes from 'prop-types';
```

`react-addons-test-utils` has moved to `react-dom/test-utils`:

```diff
-import TestUtils from 'react-addons-test-utils';
+import TestUtils from 'react-dom/test-utils';
```

**Comment by pavanmehta91** [comment]
is the development on the repo active? Is it usable with the new reactjs version. If no then we could fork and change it and make our own version. Otherwise contribute towards the issue by PRs.

**Comment by jquense** [comment]
There is already a PR for the propTypes fix. I'll take  another one switching to the createReactClass package. These are just warnings of upcoming changes. The package is still fully compatible with react 15.5

**Comment by davidgoli** [comment]
@jquense it looks like the `rm prop-types` branch got merged, but the built packages in `lib/` haven't been updated. Probably the package just needs to be built, committed, and published to npm?

**Comment by bigkrp** [comment]
I also have errors in console. It seams lib folder didn't updated

**Comment by akraines** [comment]
I just updated to 15.5.4 (from 15.3.0) and suddenly none of my multiselect widget's are working. 
I get the following error: 
Uncaught Error: traverseParentPath(...): Cannot traverse from and to the same ID, ``.
Is there something else that I need to change?

**Comment by akraines** [comment]
NM, problem is solved. Either by adding create-react-class to the project or by removing a different offending library.

**Comment by davidgoli** [comment]
@akraines ' problem may be solved, but this issue is still an issue.

**Comment by davidgoli** [comment]
@jquense would you please consider rebuilding the package to `dist/` and publishing to npm? that will fix deprecation warnings for a lot of people using your package. Thanks!

**Comment by ericvilleneuve** [comment]
I'm having the same issue with `dist` not having been updated.
Also, I couldn't find a PR or a branch for a fix to switch to the createReactClass package. Is there already an effort put towards this?

**Comment by jquense** [comment]
no one is working on the createReactClass switch for v3 v4 is already switched over.

**Comment by ericvilleneuve** [comment]
Do you think v4 is close to a release?

I tried rc5 and I noticed the warnings for `React.PropTypes` coming from `autoFocus.js`, which seems to be one of your projects as well.

**Comment by jquense** [comment]
V4 is very stable, we use it for everything at work so it's really close, just haven't had the time to do that final bump. If I missed a prop type somewhere please feel free to PR a fix

**Comment by ericvilleneuve** [comment]
Ok, I'll give another try to v4 and see how it turns out.

**Comment by ericvilleneuve** [comment]
There is a `_react2.default.PropTypes.bool` call in `autoFocus.js` from react-component-managers, which I couldn't find on GitHub.

**Comment by tomyf** [comment]
@ericvilleneuve Are you doing a PR for this one ?

**Comment by ericvilleneuve** [comment]
I couldn't get around to it but I noticed @jquense did publish an update of his [react-component-managers](https://github.com/jquense/react-component-managers) yesterday.

**Comment by ericvilleneuve** [comment]
@jquense Do you have an idea of a timeline for fixing all the warnings related to the React 15.5 update? 
We would love to update to RW v4.

**Comment by jquense** [comment]
they are all fixed in code I control in v4

**Comment by tswaters** [comment]
I figure this is as good a place to any to ask --

Are there breaking changes in v4?  I noticed there is an alpha changelog in the v4 branch but it is empty.  In your estimation how much effort will be involved moving a project from 3 to 4?

If it is a lot, or react 16 is released before v4 is published to npm under the current tag, would it be possible to publish a patch to v3 with the deprecation fixes?

**Comment by jquense** [comment]
v4 is mostly breaking in the css, the public api is pretty much the same for components unless you were using mostly undocumented extension points. Also localizers, while the same, have been moved to separate npm packages. I've upgraded all the various projects i use them in with fairly minimal effort. a few hours maybe of tweaking your themes and styles to the new classes and dom structure maybe.

**Comment by tomyf** [comment]
I migrated to v4 using small hacks.
If you need to migrate asap, add `"react-component-managers": "^3.0.1"` to your `package.json`, and perform `rimraf node_modules/react-widgets/node_modules/react-component-managers`, as react-widgets references.
I did this last friday, maybe it has changed since then.

Thankfully, there were only a few changes : merely a localizer to setup, 10 lines of CSS selectors in our Nightwatch tests and style sheets, and the trick was done :)

Thanks for not adding too many breaking changes !

**Comment by huan086** [comment]
@tomyf thanks. I end up installing react-overlays too, since the old version has prop-types problem too

added following to package.json
```js
"react-component-managers": "3.0.2",
"react-overlays": "0.7.0",
```

added following resolve.alias to webpack
```js
"react-component-managers": path.resolve(__dirname, "./node_modules/react-component-managers/lib"),
"react-overlays": path.resolve(__dirname, "./node_modules/react-overlays")
```

Really hackish solution -_-

**Comment by bigkrp** [comment]
I have 
warning.js:36 Warning: Popup: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

And i see in lib/Popup.js used deprecated createClass
https://github.com/jquense/react-widgets/blob/master/lib/Popup.js#L77

**Comment by olmobrutall** [comment]
@jquense, looks like you're pushing v4 forward, any reason not to update "react-component-managers" / "react-overlays" to remove the deprecation messages?

Thanks for your work!

**Comment by efran50** [comment]
I can see that the code was updated and React.createClass with create-react-class. But for some odd reason when I run "npm i react-widgets" on my local folder I still get the old code and the warning messages keep showing up. Do I need to run another npm command?

**Comment by tswaters** [comment]
@efran50 try `npm i react-widgets@latest`
