### ISSUE TITLE
Combobox handles Home and End keys to select items instead of only move cursor

### ISSUE THREAD

**Issue by petr-ujezdsky** [jquense/react-widgets#563]
When I want to move cursor inside the combobox via keys <kbd>Home</kbd> or <kbd>End</kbd> it selects the first or last item.

I expect the editable area to work as normal textbox with the exception of the <kbd>▲</kbd> and <kbd>▼</kbd> keys - only those keys should change item selection (with previous and next item).
Maybe the <kbd>Home</kbd> and <kbd>End</kbd> could change selection when combobox is in _expanded_ mode.

Behaviour can be easily reproduced on your [example page](http://jquense.github.io/react-widgets/docs/#/combobox?_k=t8nebc). I have tested it in browsers

- Chrome Version 57.0.2987.133 (64-bit)
- MS Internet Explorer 11 (11.0.15063.0)
- MS Edge 40.15063.0.0

**Comment by jquense** [comment]
fixed in the v4 branch

**Comment by protron** [comment]
I see this issue is still occurring on https://jquense.github.io/react-widgets/api/NumberPicker/
And I see nothing to prevent it (neither on [branch v4](https://github.com/jquense/react-widgets/blob/v4/packages/react-widgets/src/NumberPicker.js#L144) nor in [master](https://github.com/jquense/react-widgets/blob/master/packages/react-widgets/src/NumberPicker.js#L209))

@jquense Are you sure it's fixed?
